apiVersion: v1
kind: Service
metadata:
  name: {{ include "analytika.fullname" . }}-web
  labels:
    {{- include "analytika.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "analytika.web.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
